services:
  authservice:
    image: authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile

  gatewayservice:
    image: gatewayservice
    build:
      context: .
      dockerfile: GatewayService/Dockerfile

  contentservice:
    image: contentservice
    build:
      context: .
      dockerfile: ContentService/Dockerfile
