services:
  authservice:
    image: authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile

  gatewayservice:
    image: gatewayservice
    build:
      context: .
      dockerfile: GatewayService/Dockerfile
